version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:latest
    restart: unless-stopped
    depends_on:
      - postgres  # Airflow depends on Postgres being ready
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: True  # Load Airflow example DAGs (optional)
      SQL_ALCHEMY_CONN: postgresql://airflow:airflow@postgres:5432/airflow  # Postgres connection details
    volumes:
      - ./dags:/usr/local/airflow/dags  # Mount local DAGs directory
      - ./airflow.cfg:/usr/local/airflow/airflow.cfg  # Optional custom Airflow config
    ports:
      - 8080:8080  # Map Airflow webserver port to host port 8080

volumes:
  postgres_data: {}  # Define an empty volume for Postgres data persistence
